plugins {
    id 'com.android.application'
}
android {
    namespace 'com.dinius.housemaint'
    compileSdk 34
    defaultConfig {
        applicationId "com.dinius.housemaint"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release { minifyEnabled false }
    }
}
